/**
 * Run this script once to seed your Firestore with dummy ticket data.
 * Usage: node scripts/seedFirestore.mjs
 * 
 * Make sure to fill in your Firebase config in config/firebase.ts first.
 * This script uses the Firebase Admin SDK approach via REST or the client SDK.
 */

// Since this runs in Node outside Next.js, we use the firebase client SDK via dynamic import trick.
// Alternatively, paste your project ID and use the Firestore REST API.

const tickets = [
  {
    agent: "",
    assignment: [],
    attachmentLink: "false",
    dateCreated: new Date("2026-01-15T10:00:00Z"),
    email: "alice@example.com",
    folder: "Active",
    followers: ["bob@example.com"],
    lastActivity: new Date("2026-05-20T14:30:00Z"),
    lastMessage: new Date("2026-05-20T14:30:00Z"),
    madeBy: "alice@example.com",
    message: "My order hasn't arrived yet.",
    messages: [{ file_url: "", id_msg: "id_001", image_url: "", msg: "My order hasn't arrived yet.", user: "alice@example.com" }],
    name: "Alice Martin",
    priority: "Urgent",
    rating: "",
    source: "email",
    status: "open",
    subject: "Order not received",
    tags: ["shipping", "order"],
  },
  {
    agent: "bob@example.com",
    assignment: ["bob@example.com"],
    attachmentLink: "true",
    dateCreated: new Date("2026-02-10T09:15:00Z"),
    email: "charlie@example.com",
    folder: "Active",
    followers: [],
    lastActivity: new Date("2026-05-18T11:00:00Z"),
    lastMessage: new Date("2026-05-18T11:00:00Z"),
    madeBy: "charlie@example.com",
    message: "Invoice attached, please review.",
    messages: [{ file_url: "https://example.com/invoice.pdf", id_msg: "id_002", image_url: "", msg: "Invoice attached.", user: "charlie@example.com" }],
    name: "Charlie Brown",
    priority: "High",
    rating: "5",
    source: "web",
    status: "pending",
    subject: "Invoice dispute",
    tags: ["billing", "invoice"],
  },
  {
    agent: "diana@example.com",
    assignment: ["diana@example.com"],
    attachmentLink: "false",
    dateCreated: new Date("2026-03-05T08:45:00Z"),
    email: "eve@example.com",
    folder: "Active",
    followers: ["alice@example.com", "charlie@example.com"],
    lastActivity: new Date("2026-06-01T16:00:00Z"),
    lastMessage: new Date("2026-06-01T16:00:00Z"),
    madeBy: "eve@example.com",
    message: "Cannot log into my account.",
    messages: [{ file_url: "", id_msg: "id_003", image_url: "", msg: "Cannot log in.", user: "eve@example.com" }],
    name: "Eve Wilson",
    priority: "Medium",
    rating: "",
    source: "chat",
    status: "on-hold",
    subject: "Login issue",
    tags: ["account", "access"],
  },
  {
    agent: "frank@example.com",
    assignment: ["frank@example.com"],
    attachmentLink: "false",
    dateCreated: new Date("2026-04-01T12:00:00Z"),
    email: "grace@example.com",
    folder: "Active",
    followers: [],
    lastActivity: new Date("2026-05-30T10:00:00Z"),
    lastMessage: new Date("2026-05-30T10:00:00Z"),
    madeBy: "grace@example.com",
    message: "Feature request: dark mode.",
    messages: [{ file_url: "", id_msg: "id_004", image_url: "", msg: "Feature request: dark mode.", user: "grace@example.com" }],
    name: "Grace Lee",
    priority: "Low",
    rating: "4",
    source: "web",
    status: "solved",
    subject: "Dark mode request",
    tags: ["feature", "ui"],
  },
  {
    agent: "",
    assignment: [],
    attachmentLink: "false",
    dateCreated: new Date("2026-04-20T15:30:00Z"),
    email: "henry@example.com",
    folder: "Spam",
    followers: [],
    lastActivity: new Date("2026-04-20T15:30:00Z"),
    lastMessage: new Date("2026-04-20T15:30:00Z"),
    madeBy: "henry@example.com",
    message: "WIN A FREE IPHONE",
    messages: [{ file_url: "", id_msg: "id_005", image_url: "", msg: "WIN A FREE IPHONE", user: "henry@example.com" }],
    name: "Henry Spam",
    priority: "Low",
    rating: "",
    source: "email",
    status: "closed",
    subject: "You've won!!!",
    tags: [],
  },
  {
    agent: "diana@example.com",
    assignment: ["diana@example.com"],
    attachmentLink: "true",
    dateCreated: new Date("2026-05-01T09:00:00Z"),
    email: "irene@example.com",
    folder: "Active",
    followers: ["bob@example.com"],
    lastActivity: new Date("2026-06-02T09:00:00Z"),
    lastMessage: new Date("2026-06-02T09:00:00Z"),
    madeBy: "irene@example.com",
    message: "Please see attached screenshot of the bug.",
    messages: [{ file_url: "", id_msg: "id_006", image_url: "https://example.com/screenshot.png", msg: "See screenshot.", user: "irene@example.com" }],
    name: "Irene Chen",
    priority: "High",
    rating: "",
    source: "email",
    status: "open",
    subject: "UI Bug - buttons misaligned",
    tags: ["bug", "ui"],
  },
  {
    agent: "bob@example.com",
    assignment: ["bob@example.com"],
    attachmentLink: "false",
    dateCreated: new Date("2026-05-10T11:00:00Z"),
    email: "jack@example.com",
    folder: "Archive",
    followers: [],
    lastActivity: new Date("2026-05-25T12:00:00Z"),
    lastMessage: new Date("2026-05-25T12:00:00Z"),
    madeBy: "jack@example.com",
    message: "Refund processed, closing ticket.",
    messages: [{ file_url: "", id_msg: "id_007", image_url: "", msg: "Refund processed.", user: "bob@example.com" }],
    name: "Jack Turner",
    priority: "Medium",
    rating: "5",
    source: "phone",
    status: "solved",
    subject: "Refund request",
    tags: ["refund", "billing"],
  },
  {
    agent: "",
    assignment: [],
    attachmentLink: "false",
    dateCreated: new Date("2026-06-01T08:00:00Z"),
    email: "karen@example.com",
    folder: "Active",
    followers: ["diana@example.com"],
    lastActivity: new Date("2026-06-03T08:00:00Z"),
    lastMessage: new Date("2026-06-03T08:00:00Z"),
    madeBy: "karen@example.com",
    message: "App crashes on startup.",
    messages: [{ file_url: "", id_msg: "id_008", image_url: "", msg: "App crashes on startup.", user: "karen@example.com" }],
    name: "Karen Patel",
    priority: "Urgent",
    rating: "",
    source: "chat",
    status: "open",
    subject: "App crash on launch",
    tags: ["bug", "crash", "mobile"],
  },
];

console.log("Dummy ticket data ready. Copy this and import via Firebase Console or use the Firestore REST API.");
console.log(JSON.stringify(tickets, null, 2));
